### PR TITLE
partial updates

### PR DESCRIPTION
**Pull request by yaakovs**

### CODE REVIEW

**Comment by mutayroei** [comment]
Can you add the update request to the gRPC version of the index as well? pinecone/core/grpc/index_grpc.py. The interface should be similar to the upsert API, including async_req option

**Comment by rajat08** [comment]
@yaakovs  I dont see the updated spec files, did you forget to add them?

**Comment by mutayroei** [comment]
> @yaakovs I dont see the updated spec files, did you forget to add them?

https://github.com/pinecone-io/pinecone-python-client/pull/48/files

**Comment by mutayroei** [comment]
@rajat08 the docs are synced with the client repo or with the core repo?

**Comment by rajat08** [comment]
@mutayroei they are in both places at the moment, but make gen does change them simultaneously. Also didn't see Yaakov's other PR in the client repo

**Review by rajat08 — APPROVED** [review]

**Comment by mutayroei** [comment]
> @mutayroei they are in both places at the moment, but make gen does change them simultaneously. Also didn't see Yaakov's other PR in the client repo
 I meant to ask - which one of them is the source for Redocly portal?

**Pull request merged**
