### PR TITLE
Adds the ability to specifiy metadata index configuration

### PR DESCRIPTION
**Pull request by AdamGS**

### CODE REVIEW

**Comment by rajat08** [comment]
hey @AdamGS , I think this would need a change in the spec in the backend too. Is there a PR in core related to this?

**Review by rajat08 — APPROVED** [review]

**Comment by rajat08** [comment]
@AdamGS 
Can you some details about in the changelog? You can create a header called Changed and put a couple of lines there

**Comment by rajat08** [comment]
> @AdamGS Can you some details about in the changelog? You can create a header called Changed and put a couple of lines there

Should be good to merge after that!

**Comment by mutayroei** [comment]
@AdamGS can you add the relevant changes to the CHANGELOG and merge?

**Comment by AdamGS** [comment]
I also added @byronnlandry change to the OpenAPI spec

**Pull request merged**
